### PR TITLE
Update Arabic language definition

### PR DESCRIPTION
**Pull request by waddyhussain**
I edited the file manually instead of generating with the script (since I'm running Lute with docker so couldn't use the python command in the README), but it passes the verify files test.

There might be too many dictionaries now, but I didn't want to remove any of the existing ones since I wasn't the one who added them (personally I find the 3 I added and Google translate to be most useful).

Also, the reason for all the extra query parameters with livingarabic is to disable searching example sentences in the filter options. Having it enabled usually, clutters the results with loads of unrelated words, so I thought for most people it makes sense to have it disabled as the default.

### CODE REVIEW

**Comment by jzohrab** [comment]
Ah, sorry @waddyhussain that I missed this PR!  I've changed some things so now this has a conflict.  If you have a moment can you look into it?  Apologies again for dropping it :-/

**Comment by waddyhussain** [comment]
No worries @jzohrab, conflicts were just because of the new placeholder for dictionary URLs, so have updated to use the new one.

Let me know if you need any other changes

**Comment by jzohrab** [comment]
Thanks again, sorry for the delay in incorporating.  Will try it out, looks good to me!

**Comment by jzohrab** [comment]
The context.reverso.net didn't work as embedded for me.  I see many other lang defs have it as embedded as well, maybe they changed their policy recently or something.  Other than that, looks good, thank you!

**Comment by waddyhussain** [comment]
Thank you!

Yeah just checked and also isn't working for me, was either a mistake on my part or policy changed like you said. Feel free to update to popup

**Comment by jzohrab** [comment]
Released in 3.6.1.

**Pull request merged**
